#!/bin/bash
# Clone + install BiguaSim INSIDE the running container. Run this once (or
# after removing the container). It is a separate step, not baked into the
# image, because BiguaSim is a fast-moving research dependency -- updating it
# afterwards is `git -C ~/biguasim/src pull` + rebuild, not an image rebuild.
#
# Usage (inside the container):
#   BIGUASIM_REPO=git@github.com:<org>/<biguasim>.git install_biguasim.sh
#   # or, if it needs a specific branch:
#   BIGUASIM_REPO=... BIGUASIM_BRANCH=dev install_biguasim.sh
#
# What it does, in order:
#   1. git clone $BIGUASIM_REPO  -> ~/biguasim/src
#   2. auto-detects how to install it:
#        - has package.xml (ROS 2 pkg)      -> symlink into
#          ~/workspaces/biguasim_ws/src and tell you to `colcon build`
#        - has setup.py / pyproject.toml    -> pip install -e (user)
#        - has requirements.txt             -> pip install -r
#        - has a CMakeLists.txt at the root -> cmake+make into ~/biguasim/install
#      (multiple can apply; all are attempted)
#   3. writes ~/biguasim/setup.bash so the entrypoint / .bashrc can source it
#
# If BiguaSim's real layout does not match any of these, edit the "manual
# steps" section printed at the end -- this script is a starting point, not a
# guarantee.
set -euo pipefail

BIGUASIM_ROOT="${BIGUASIM_ROOT:-$HOME/biguasim}"
SRC_DIR="$BIGUASIM_ROOT/src"
WS_SRC="${WS_SRC:-$HOME/workspaces/biguasim_ws/src}"

if [ -z "${BIGUASIM_REPO:-}" ]; then
    cat >&2 <<'EOF'
ERROR: BIGUASIM_REPO is not set.

  Set it to BiguaSim's git URL and re-run, e.g.:
    BIGUASIM_REPO=https://github.com/<org>/<biguasim>.git install_biguasim.sh

  (Optional: BIGUASIM_BRANCH=<branch>, BIGUASIM_ROOT=<dir>.)
EOF
    exit 1
fi

mkdir -p "$BIGUASIM_ROOT"

# ---- 1. clone / update ----------------------------------------------------
if [ -d "$SRC_DIR/.git" ]; then
    echo ">> BiguaSim already cloned at $SRC_DIR -- pulling"
    git -C "$SRC_DIR" pull --ff-only || echo "   (pull skipped)"
else
    echo ">> cloning $BIGUASIM_REPO -> $SRC_DIR"
    git clone ${BIGUASIM_BRANCH:+-b "$BIGUASIM_BRANCH"} "$BIGUASIM_REPO" "$SRC_DIR"
fi

# ---- 2. install, best-effort autodetect ---------------------------------
did_something=0

# system deps declared by the repo (rosdep), non-fatal
if [ -f "$SRC_DIR/package.xml" ] || ls "$SRC_DIR"/*/package.xml >/dev/null 2>&1; then
    echo ">> rosdep install for BiguaSim ROS 2 package(s)"
    sudo apt-get update -qq || true
    rosdep install --from-paths "$SRC_DIR" --ignore-src -y || \
        echo "   (rosdep reported unresolved keys -- continue and fix by hand if the build fails)"

    echo ">> linking BiguaSim ROS 2 package(s) into $WS_SRC/biguasim_upstream"
    mkdir -p "$WS_SRC"
    ln -sfn "$SRC_DIR" "$WS_SRC/biguasim_upstream"
    echo "   -> next: cd ~/workspaces/biguasim_ws && colcon build --symlink-install"
    did_something=1
fi

if [ -f "$SRC_DIR/setup.py" ] || [ -f "$SRC_DIR/pyproject.toml" ]; then
    echo ">> pip install -e $SRC_DIR"
    pip install --user -e "$SRC_DIR"
    did_something=1
fi

if [ -f "$SRC_DIR/requirements.txt" ]; then
    echo ">> pip install -r requirements.txt"
    pip install --user -r "$SRC_DIR/requirements.txt"
    did_something=1
fi

if [ -f "$SRC_DIR/CMakeLists.txt" ] && [ ! -f "$SRC_DIR/package.xml" ]; then
    echo ">> cmake build $SRC_DIR -> $BIGUASIM_ROOT/build|install"
    cmake -S "$SRC_DIR" -B "$BIGUASIM_ROOT/build" -DCMAKE_INSTALL_PREFIX="$BIGUASIM_ROOT/install"
    cmake --build "$BIGUASIM_ROOT/build" --target install -j"$(nproc)"
    did_something=1
fi

# ---- 3. env file --------------------------------------------------------
{
    echo "# Auto-generated by install_biguasim.sh"
    echo "export BIGUASIM_ROOT=\"$BIGUASIM_ROOT\""
    [ -d "$BIGUASIM_ROOT/install" ] && \
        echo "export PATH=\"$BIGUASIM_ROOT/install/bin:\$PATH\"" && \
        echo "export LD_LIBRARY_PATH=\"$BIGUASIM_ROOT/install/lib:\${LD_LIBRARY_PATH:-}\""
    echo "# Add BiguaSim-specific exports below (world paths, sim host/port, etc.)"
} > "$BIGUASIM_ROOT/setup.bash"

echo
if [ "$did_something" -eq 0 ]; then
    cat <<EOF
>> Cloned to $SRC_DIR but no known install layout was detected.
   Finish by hand, then add the needed exports to $BIGUASIM_ROOT/setup.bash:
     - if it is an Unreal project / packaged binary: note its run command
     - if it is a ROS 2 package in a subfolder: ln -sfn <subfolder> $WS_SRC/
EOF
else
    echo ">> BiguaSim installed. Re-enter the container (or 'source $BIGUASIM_ROOT/setup.bash')."
fi
